name: lab4
services:
  nginx:
    image: "nginx:1.25"
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    depends_on:
      - flask

  flask:
    # image: "aquaman/flask:1.0"
    build: .
    container_name: flask
    env_file:
      - .env
    secrets:
      - sql_secret
    ports:
      - "5000:5000"
    command: flask --app flask_app run --host=0.0.0.0
    # command: sleep infinity
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: "postgres:16.1-alpine"
    container_name: postgres
    env_file:
      - .env
    secrets:
      - postgres_secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    entrypoint: >
      sh -c "
      export POSTGRES_PASSWORD=$(cat /run/secrets/postgres_secret) &&
      docker-entrypoint.sh postgres &&
      unset POSTGRES_PASSWORD"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d flask_db -U flask_user"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:

secrets:
  sql_secret:
    file: ./secrets/sql_pass
  postgres_secret:
    file: ./secrets/postgres_pass